apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    role: locust-slave
  name: locust-slave
spec:
  replicas: {{ .Values.replicaCountSlave }}
  selector:
    matchLabels:
      role: locust-slave
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: locust-slave
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: locust-slave
        env:
          - name: ATTACKED_HOST
            value: {{ .Values.AttackHost }}
          - name: LOCUST_MODE
            value: locust-slave
          - name: LOCUST_MASTER
            value: locust-master
          - name: LOCUST_MASTER_BIND_PORT
            value: "5557"
          - name: QUIET_MODE
            value: "${QUIET_MODE:-false}"
          - name: LOCUST_OPTS
            value: "--csv=example"
          - name: NO_PROXY
            value: locust-master
          - name: ES_CONNECTIONS
            valueFrom:
              configMapKeyRef:
                name: locust-es-cm
                key: ES_CONNECTIONS
        volumeMounts:
          - mountPath: /locust
            name: locust-scripts
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      nodeSelector: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: locust-scripts
        configMap:
          name: scripts-cm
